ValueSet: Example_Lab_Obs_Test_Name_Triggers_for_Public_Health_Reporting
Id: valueset-lrtc-example
Title: "Example Lab Obs Test Name Triggers for Public Health Reporting"
Description: "This example set of values contains laboratory observations test names that represent that the patient may have a potentially reportable condition regardless of the clinical presentation of the condition"
* ^meta.profile = "http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-triggering-valueset"
* ^extension[0].url = "http://hl7.org/fhir/StructureDefinition/valueset-steward"
* ^extension[=].valueContactDetail.name = "CSTE Steward"
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/valueset-author"
* ^extension[=].valueContactDetail.name = "CSTE Author"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:2.16.840.1.113762.1.4.1146.1057"
* ^version = "1.0.0"
* ^status = #draft
* ^experimental = true
* ^date = "2018-08-01"
* ^publisher = "{site.data.fhir.ig.publisher}"
* ^useContext[0].code = $USPublicHealthUsageContextType#reporting "Reporting"
* ^useContext[=].valueCodeableConcept = $USPublicHealthUsageContext#triggering "Triggering"
* ^useContext[+].code = $USPublicHealthUsageContextType#priority "Priority"
* ^useContext[=].valueCodeableConcept = $USPublicHealthUsageContext#routine "Routine"
* ^jurisdiction = urn:iso:std:iso:3166#US "United States of America"
* ^jurisdiction.text = "United States of America"
* ^copyright = "This material contains content from LOINC (http://loinc.org). LOINC is copyright © 1995-2020, Regenstrief Institute, Inc. and the Logical Observation Identifiers Names and Codes (LOINC) Committee and is available at no cost under the license at http://loinc.org/license. LOINC® is a registered United States trademark of Regenstrief Institute, Inc"
* LOINC#11585-7 "Bordetella pertussis Ab [Units/volume] in Serum"
* LOINC#14127-5 "Neisseria gonorrhoeae [Presence] in Anal by Organism specific culture"
* LOINC#14461-8 "Chlamydia trachomatis [Presence] in Blood by Organism specific culture"
* LOINC#14462-6 "Chlamydia trachomatis [Presence] in Cerebral spinal fluid by Organism specific culture"
* LOINC#14463-4 "Chlamydia trachomatis [Presence] in Cervix by Organism specific culture"