Instance: bundle-eicr-document-zika
InstanceOf: EICRDocumentBundle
Title: "eICR Document Bundle Example: bundle-eicr-document-zika"
Description: "Example of eICR Document Bundle profile (Eve Everywoman, Zika)"
Usage: #example
* identifier.system = "urn:ietf:rfc:3986"
* identifier.value = "urn:uuid:2be4b4e4-6df1-4cb2-a947-c70fa0eda54b"
* type = #document
* timestamp = "2021-08-02T22:13:23Z"
* entry[0].fullUrl = "http://example.org/fhir/Composition/composition-eicr-zika"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-1
* entry[+].fullUrl = "http://example.org/fhir/MedicationAdministration/medicationadministration-eve-everywoman-azithromycin"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-2
* entry[+].fullUrl = "http://example.org/fhir/Procedure/us-ph-procedure-ecmo"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-3
* entry[+].fullUrl = "http://example.org/fhir/MedicationAdministration/medicationadministration-eve-everywoman-naloxone-response"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-4
* entry[+].fullUrl = "http://example.org/fhir/ServiceRequest/servicerequest-eicr-zika"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-5
* entry[+].fullUrl = "http://example.org/fhir/Condition/condition-eicr-eve-everywoman-common-cold"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-6
* entry[+].fullUrl = "http://example.org/fhir/Encounter/encounter-eicr-eve-everywoman-outpatient"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-7
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-pregnancy-status-eve-everywoman"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-8
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-vaccine-credential-assertion-eve-everywoman"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-9
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-us-ph-emergency-outbreak-info-eve-everywoman"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-10
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-country-of-nationality-eve-everywoman"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-11
* entry[+].fullUrl = "http://example.org/fhir/Patient/patient-ecr-eve-everywoman"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-12
* entry[+].fullUrl = "http://example.org/fhir/Immunization/immunization-ecr-pneumo"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-13
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-country-of-residence-eve-everywoman"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-14
* entry[+].fullUrl = "http://example.org/fhir/PractitionerRole/practitionerrole-henry-seven"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-15
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-blood-pressure-eve-everywoman"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-16
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-us-ph-exposure-contact-info-football-game"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-17
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-travel-history-eve-everywoman-201801"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-18
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-disability-status-eve-everywoman"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-19
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-us-ph-lab-result-eve-everywoman-lymphocytes"
* entry[=].resource = observation-us-ph-lab-result-eve-everywoman-lymphocytes
* entry[+].fullUrl = "http://example.org/fhir/Organization/organization-ecr-acme-laboratory"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-21
* entry[+].fullUrl = "http://example.org/fhir/Location/location-ecr-salem-medical-center"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-22
* entry[+].fullUrl = "http://example.org/fhir/Location/location-ecr-city-football-stadium"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-23
* entry[+].fullUrl = "http://example.org/fhir/Organization/organization-ecr-salem-medical-center"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-24
* entry[+].fullUrl = "http://example.org/fhir/Condition/condition-eicr-eve-everywoman-zika"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-25
* entry[+].fullUrl = "http://example.org/fhir/Practitioner/practitioner-us-core-henry-seven"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-26
* entry[+].fullUrl = "http://example.org/fhir/Device/device-ecmo"
* entry[=].resource = Inline-Instance-for-bundle-eicr-document-zika-27