Instance: bundle-eicr-document-zika
InstanceOf: EICRDocumentBundle
Title: "eICR Document Bundle Example: bundle-eicr-document-zika"
Description: "Example of eICR Document Bundle profile (Eve Everywoman, Zika)"
Usage: #example
* identifier.system = "urn:ietf:rfc:3986"
* identifier.value = "urn:uuid:2be4b4e4-6df1-4cb2-a947-c70fa0eda54b"
* type = #document
* timestamp = "2021-08-02T22:13:23Z"
* entry[0].fullUrl = "http://example.org/fhir/Composition/composition-eicr-zika"
* entry[=].resource = composition-eicr-zika
* entry[+].fullUrl = "http://example.org/fhir/MedicationAdministration/medicationadministration-eve-everywoman-azithromycin"
* entry[=].resource = medicationadministration-eve-everywoman-azithromycin
* entry[+].fullUrl = "http://example.org/fhir/Procedure/us-ph-procedure-ecmo"
* entry[=].resource = us-ph-procedure-ecmo
* entry[+].fullUrl = "http://example.org/fhir/MedicationAdministration/medicationadministration-eve-everywoman-naloxone-response"
* entry[=].resource = medicationadministration-eve-everywoman-naloxone-response
* entry[+].fullUrl = "http://example.org/fhir/ServiceRequest/servicerequest-eicr-zika"
* entry[=].resource = servicerequest-eicr-zika
* entry[+].fullUrl = "http://example.org/fhir/Condition/condition-eicr-eve-everywoman-common-cold"
* entry[=].resource = condition-eicr-eve-everywoman-common-cold
* entry[+].fullUrl = "http://example.org/fhir/Encounter/encounter-eicr-eve-everywoman-outpatient"
* entry[=].resource = encounter-eicr-eve-everywoman-outpatient
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-pregnancy-status-eve-everywoman"
* entry[=].resource = observation-pregnancy-status-eve-everywoman
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-vaccine-credential-assertion-eve-everywoman"
* entry[=].resource = observation-vaccine-credential-assertion-eve-everywoman
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-us-ph-emergency-outbreak-info-eve-everywoman"
* entry[=].resource = observation-us-ph-emergency-outbreak-info-eve-everywoman
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-country-of-nationality-eve-everywoman"
* entry[=].resource = observation-country-of-nationality-eve-everywoman
* entry[+].fullUrl = "http://example.org/fhir/Patient/patient-ecr-eve-everywoman"
* entry[=].resource = patient-ecr-eve-everywoman
* entry[+].fullUrl = "http://example.org/fhir/Immunization/immunization-ecr-pneumo"
* entry[=].resource = immunization-ecr-pneumo
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-country-of-residence-eve-everywoman"
* entry[=].resource = observation-country-of-residence-eve-everywoman
* entry[+].fullUrl = "http://example.org/fhir/PractitionerRole/practitionerrole-henry-seven"
* entry[=].resource = practitionerrole-henry-seven
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-blood-pressure-eve-everywoman"
* entry[=].resource = observation-blood-pressure-eve-everywoman
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-us-ph-exposure-contact-info-football-game"
* entry[=].resource = observation-us-ph-exposure-contact-info-football-game
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-travel-history-eve-everywoman-201801"
* entry[=].resource = observation-travel-history-eve-everywoman-201801
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-disability-status-eve-everywoman"
* entry[=].resource = observation-disability-status-eve-everywoman
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-us-ph-lab-result-eve-everywoman-lymphocytes"
* entry[=].resource = observation-us-ph-lab-result-eve-everywoman-lymphocytes
* entry[+].fullUrl = "http://example.org/fhir/Organization/organization-ecr-acme-laboratory"
* entry[=].resource = organization-ecr-acme-laboratory
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-odh-usual-work-eve-everywoman"
* entry[=].resource = observation-odh-usual-work-eve-everywoman
* entry[+].fullUrl = "http://example.org/fhir/Location/location-ecr-salem-medical-center"
* entry[=].resource = location-ecr-salem-medical-center
* entry[+].fullUrl = "http://example.org/fhir/Location/location-ecr-city-football-stadium"
* entry[=].resource = location-ecr-city-football-stadium
* entry[+].fullUrl = "http://example.org/fhir/Organization/organization-ecr-salem-medical-center"
* entry[=].resource = organization-ecr-salem-medical-center
* entry[+].fullUrl = "http://example.org/fhir/Condition/condition-eicr-eve-everywoman-zika"
* entry[=].resource = condition-eicr-eve-everywoman-zika
* entry[+].fullUrl = "http://example.org/fhir/Practitioner/practitioner-us-core-henry-seven"
* entry[=].resource = practitioner-us-core-henry-seven
* entry[+].fullUrl = "http://example.org/fhir/Device/device-ecmo"
* entry[=].resource = device-ecmo