Instance: composition-rr-single-single-html-validation-output
InstanceOf: RRComposition
Title: "Reportability Response - One Condition/One PHA with eICR Validation Output example"
Description: "Example of Reportability Response Composition - One Condition/One PHA with eICR Validation Output"
Usage: #example
* extension[0].url = "http://hl7.org/fhir/StructureDefinition/composition-clinicaldocument-versionNumber"
* extension[=].valueString = "1"
* extension[+].url = "http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-information-recipient-extension"
* extension[=].valueReference.reference = "PractitionerRole/practitionerrole-henry-seven"
* identifier.system = "http://acme.org/identifiers"
* identifier.value = "RR9875"
* status = #final
* type = $loinc#88085-6 "Reportability response report Document Public health"
* subject.reference = "Patient/patient-ecr-eve-everywoman"
* subject.display = "Eve Everywoman"
* encounter.reference = "Encounter/encounter-eicr-eve-everywoman-outpatient"
* encounter.display = "Ambulatory Office Visit"
* date = "2018-07-19T04:09:06Z"
* author.reference = "Organization/organization-ecr-health-authority-west"
* author.display = "Health Authority West, 7777 Health Authority Drive, Ann Arbor MI, 99999"
* title = "Reportability Response - One Condition/One PHA with eICR Validation Output example"
* custodian.reference = "Organization/organization-ecr-health-authority-west"
* custodian.display = "Health Authority West, 7777 Health Authority Drive, Ann Arbor MI, 99999"
* section[0].title = "Reportability Response Subject Section"
* section[=].code = $loinc#88084-9 "Reportable condition response information and summary Document"
* section[=].text.status = #generated
* section[=].text.div = "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p>Public Health Reporting Communication: one or more conditions are reportable, or may be reportable to public health</p></div>"
* section[sliceEICRSection].extension[0].extension[0].url = "eICRProcessingStatus"
* section[sliceEICRSection].extension[=].extension[=].valueReference.reference = "Observation/observation-rr-eicr-processing-status"
* section[sliceEICRSection].extension[=].extension[=].valueReference.display = "eICR was processed - with a warning"
* section[sliceEICRSection].extension[=].extension[+].url = "eICRValidationOutput"
* section[sliceEICRSection].extension[=].extension[=].valueMarkdown = "<html\n\n\n\n\n\n\n\n\n\n\n\r\n                    xmlns='http://www.w3.org/1999/xhtml'\n\n\n\n\n\n\n\n\n\n\n\r\n                    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>\n                <head>\n                  <title> Results </title><style type='text/css'> </style></head>\n                <body>\n                  <table>\n                    <thead>\n                      <tr>\n                        <th>Severity</th>\n                        <th>Description</th>\n                        <th>File</th>\n                        <th>Location</th>\n                      </tr>\n                    </thead>\n                    <tbody>\n                      <tr>\n                        <td>error</td>\n                        <td>SHOULD contain zero or one [0..1] setId (CONF:1098-32752).</td>\n                        <td>C:\\Users\\user1\\Documents\\Work\\Lantana\\SVN\\ClientProjects\\ReportabilityResponse\\xml\\samples\\CDAR2_IG_PHCR_R2_RR_D1_2017AUG_SAMPLE.xml</td>\n                        <td>\n                          <p>Start line 415:70</p>\n                        </td>\n                      </tr>\n                      <tr>\n                        <td>error</td>\n                        <td>SHOULD contain zero or one [0..1] versionNumber (CONF:1098-32753).</td>\n                        <td>C:\\Users\\user1\\Documents\\Work\\Lantana\\SVN\\ClientProjects\\ReportabilityResponse\\xml\\samples\\CDAR2_IG_PHCR_R2_RR_D1_2017AUG_SAMPLE.xml</td>\n                        <td>\n                          <p>Start line 415:70</p>\n                        </td>\n                      </tr>\n                    </tbody>\n                  </table>\n                </body>\n              </html>"
* section[sliceEICRSection].extension[=].url = "http://hl7.org/fhir/us/ecr/StructureDefinition/rr-eicr-processing-status-extension"
* section[sliceEICRSection].extension[+].url = "http://hl7.org/fhir/us/ecr/StructureDefinition/rr-eicr-receipt-time-extension"
* section[sliceEICRSection].extension[=].valueDateTime = "2018-07-18T04:09:06Z"
* section[sliceEICRSection].title = "Electronic Initial Case Report Section"
* section[sliceEICRSection].code = $loinc#88082-3 "Initial case report processing information Document"
* section[=].entry.reference = "Bundle/bundle-eicr-document-zika"
* section[=].entry.identifier.system = "urn:ietf:rfc:3986"
* section[=].entry.identifier.value = "urn:uuid:0070e7b2-9893-4044-b255-73da1649c9fe"
* section[=].entry.display = "bundle-eicr-document-zika.xml"
* section[+].extension.url = "http://hl7.org/fhir/us/ecr/StructureDefinition/rr-priority-extension"
* section[=].extension.valueCodeableConcept = urn:oid:2.16.840.1.114222.4.5.274#RRVS17 "Immediate action required"
* section[=].title = "Reportability Response Summary Section"
* section[=].code = $loinc#55112-7 "Document summary"
* section[=].text.status = #generated
* section[=].text.div = "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>Summary:</b></p><p>Your organization electronically submitted an initial case report to determine if reporting to public health is needed for a patient. \"Zika virus disease (disorder)\" is reportable to \"State\r\n                    Department of Health\". An initial case report was sent to \"State Department of Health\". Additional information may be required for this report. <br/><br/></p><p><b>\"Zika virus disease (disorder)\" for \"State Department of Health\"</b></p><p>Reporting is required within \"24 hours\". Reporting to this Public Health Agency is based on \"both patient home address and provider facility address\". </p><ul><li><p>Local mosquito-borne Zika virus transmission was reported in your area. Increased watchfulness for symptoms of Zika virus in your patients is warranted. (Immediate action\r\n                            requested)</p></li><li><p>Additional information for the required reporting of Zika must be submitted to State Department of Health immediately. This additional information can be submitted here. ( <a href=\"http://statedepartmentofhealth.gov/epi/disease/zika/Supplemental_data_form.pdf\">Link</a> - Immediate action required) </p></li><li><p>Zika has particular risks for pregnant women. Follow-up guidance for pregnant women and couples who are planning pregnancy. ( <a href=\"http://statedepartmentofhealth.gov/epi/diseases/zika/Zika_Virus_Testing_Guidance.pdf\">Link</a> - Immediate action requested) </p></li><li><p>Further Laboratory testing for Zika may be needed. Guidance for additional testing and specimen collection ( <a href=\"http://statedepartmentofhealth.gov/epi/diseases/zika/Zika_Virus_Testing_Guidance.pdf\">Link</a> - Action requested) </p></li><li><p>Forms for submitting further Zika laboratory testing ( <a href=\"http://statedepartmentofhealth.gov/epi/diseases/zika/zika_test_request_form_UPHL.xlsx\">Link</a> - Information only)\r\n                        </p></li><li><p>Treatment guidance ( <a href=\"http://statedepartmentofhealth.gov/epi/diseases/zika/Zika_Virus_Testing_Guidance.pdf\">Link</a> - Information only) </p></li><li><p>If you have additional questions regarding Zika or reporting, contact information for the State Department of Health is available here. ( <a href=\"http://statedepartmentofhealth.gov/epi/diseases/zika/Zika_Virus_Testing_Guidance.pdf\">Link</a> - Information Only) </p></li></ul><p>Additional Resources (Information only):</p><ul><li><p>Control and prevention information for providers ( <a href=\"http://statedepartmentofhealth.gov/epi/diseases/zika/plan.pdf\">Link</a>) </p></li><li><p>Detailed condition references ( <a href=\"http://statedepartmentofhealth.gov/epi/diseases/zika/plan.pdf\">Link</a>) </p></li><li><p>Prevalence in State ( <a href=\"http://statedepartmentofhealth.gov/epi/diseases/zika/plan.pdf\">Link</a>) </p></li><li><p>CDC webpage ( <a href=\"https://www.cdc.gov/zika/index.html\">Link</a>) </p></li><li><p>Patient information factsheet ( <a href=\"http://statedepartmentofhealth.gov/epi/diseases/zika/factsheet.pdf\">Link</a>) </p></li><li><p>State Resident information ( <a href=\"http://statedepartmentofhealth.gov/epi/diseases/zika/ZikaVirus_QA_StateDOH.pdf\">Link</a>) </p></li></ul></div>"
* section[=].entry[0].reference = "Observation/observation-rr-summary"
* section[=].entry[=].display = "Reportability Response Summary"
* section[=].entry[+].reference = "Observation/observation-rr-relevant-reportable-condition-observation"
* section[=].entry[=].display = "Relevant reportable condition: Zika"