Instance: composition-rr-one-cond-one-pha
InstanceOf: RRComposition
Title: "Reportability Response Composition - One Condition/One PHA example"
Description: "Example of Reportability Response Composition - One Condition/One PHA"
Usage: #example
* extension[0].url = "http://hl7.org/fhir/StructureDefinition/composition-clinicaldocument-versionNumber"
* extension[=].valueString = "1"
* extension[+].url = "http://hl7.org/fhir/us/ph-library/StructureDefinition/us-ph-information-recipient-extension"
* extension[=].valueReference.reference = "PractitionerRole/practitionerrole-henry-seven"
* identifier.system = "http://acme.org/identifiers"
* identifier.value = "RR12347"
* status = #final
* type = $loinc#88085-6 "Reportability response report Document Public health"
* subject.reference = "Patient/patient-ecr-eve-everywoman"
* subject.display = "Eve Everywoman"
* encounter.reference = "Encounter/encounter-eicr-eve-everywoman-outpatient"
* encounter.display = "Ambulatory Office Visit"
* date = "2018-07-19T04:09:06Z"
* author.reference = "Organization/organization-ecr-health-authority-west"
* author.display = "Health Authority West, 7777 Health Authority Drive, Ann Arbor MI, 99999"
* title = "Reportability Response - One Condition/One PHA example"
* custodian.reference = "Organization/organization-ecr-health-authority-west"
* custodian.display = "Health Authority West, 7777 Health Authority Drive, Ann Arbor MI, 99999"
* section[sliceRRSubjectSection].title = "Reportability Response Subject Section"
* section[sliceRRSubjectSection].code = $loinc#88084-9 "Reportable condition response information and summary Document"
* section[sliceRRSubjectSection].text.status = #generated
* section[sliceRRSubjectSection].text.div = "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p>Public Health Reporting Communication: one or more conditions are reportable, or may be reportable to public health</p></div>"
* section[sliceEICRSection].extension[0].extension[0].url = "eICRProcessingStatus"
* section[sliceEICRSection].extension[=].extension[=].valueReference.reference = "Observation/observation-rr-eicr-processing-status"
* section[sliceEICRSection].extension[=].extension[=].valueReference.display = "eICR was processed - with a warning"
* section[sliceEICRSection].extension[=].extension[+].url = "eICRValidationOutput"
* section[sliceEICRSection].extension[=].extension[=].valueAttachment.contentType = #text/html
* section[sliceEICRSection].extension[=].extension[=].valueAttachment.data = "PGh0bWwgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGh0bWwiIHhtbG5zOnhzaT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEtaW5zdGFuY2UiPg0KICAgICAgICAgIDxoZWFkPg0KICAgICAgICAgICAgPHRpdGxlPiBSZXN1bHRzIDwvdGl0bGU+DQogICAgICAgICAgICA8c3R5bGUgdHlwZT0idGV4dC9jc3MiPiA8L3N0eWxlPg0KICAgICAgICAgIDwvaGVhZD4NCiAgICAgICAgICA8Ym9keT4NCiAgICAgICAgICAgIDx0YWJsZT4NCiAgICAgICAgICAgICAgPHRoZWFkPg0KICAgICAgICAgICAgICAgIDx0cj4NCiAgICAgICAgICAgICAgICAgIDx0aD5TZXZlcml0eTwvdGg+DQogICAgICAgICAgICAgICAgICA8dGg+RGVzY3JpcHRpb248L3RoPg0KICAgICAgICAgICAgICAgICAgPHRoPkZpbGU8L3RoPg0KICAgICAgICAgICAgICAgICAgPHRoPkxvY2F0aW9uPC90aD4NCiAgICAgICAgICAgICAgICA8L3RyPg0KICAgICAgICAgICAgICA8L3RoZWFkPg0KICAgICAgICAgICAgICA8dGJvZHk+DQogICAgICAgICAgICAgICAgPHRyPg0KICAgICAgICAgICAgICAgICAgPHRkPmVycm9yPC90ZD4NCiAgICAgICAgICAgICAgICAgIDx0ZD5TSE9VTEQgY29udGFpbiB6ZXJvIG9yIG9uZSBbMC4uMV0gc2V0SWQgKENPTkY6MTA5OC0zMjc1MikuPC90ZD4NCiAgICAgICAgICAgICAgICAgIDx0ZD5DREFSMl9JR19QSENSX1IyX1JSX0QxXzIwMTdPQ1RfU0FNUExFLnhtbDwvdGQ+DQogICAgICAgICAgICAgICAgICA8dGQ+DQogICAgICAgICAgICAgICAgICAgIDxwPlN0YXJ0IGxpbmUgNDE1OjcwPC9wPg0KICAgICAgICAgICAgICAgICAgPC90ZD4NCiAgICAgICAgICAgICAgICA8L3RyPg0KICAgICAgICAgICAgICAgIDx0cj4NCiAgICAgICAgICAgICAgICAgIDx0ZD5lcnJvcjwvdGQ+DQogICAgICAgICAgICAgICAgICA8dGQ+U0hPVUxEIGNvbnRhaW4gemVybyBvciBvbmUgWzAuLjFdIHZlcnNpb25OdW1iZXIgKENPTkY6MTA5OC0zMjc1MykuPC90ZD4NCiAgICAgICAgICAgICAgICAgIDx0ZD5DREFSMl9JR19QSENSX1IyX1JSX0QxXzIwMTdPQ1RfU0FNUExFLnhtbDwvdGQ+DQogICAgICAgICAgICAgICAgICA8dGQ+DQogICAgICAgICAgICAgICAgICAgIDxwPlN0YXJ0IGxpbmUgNDE1OjcwPC9wPg0KICAgICAgICAgICAgICAgICAgPC90ZD4NCiAgICAgICAgICAgICAgICA8L3RyPg0KICAgICAgICAgICAgICA8L3Rib2R5Pg0KICAgICAgICAgICAgPC90YWJsZT4NCiAgICAgICAgICA8L2JvZHk+DQogICAgICAgIDwvaHRtbD4="
* section[sliceEICRSection].extension[=].url = "http://hl7.org/fhir/us/ecr/StructureDefinition/rr-eicr-processing-status-extension"
* section[sliceEICRSection].extension[+].url = "http://hl7.org/fhir/us/ecr/StructureDefinition/rr-eicr-receipt-time-extension"
* section[sliceEICRSection].extension[=].valueDateTime = "2018-07-18T04:09:06Z"
* section[sliceEICRSection].title = "Electronic Initial Case Report Section"
* section[sliceEICRSection].code = $loinc#88082-3 "Initial case report processing information Document"
* section[sliceEICRSection].entry.reference = "Bundle/bundle-eicr-document-zika"
* section[sliceEICRSection].entry.identifier.system = "urn:ietf:rfc:3986"
* section[sliceEICRSection].entry.identifier.value = "urn:uuid:0070e7b2-9893-4044-b255-73da1649c9fe"
* section[sliceEICRSection].entry.display = "bundle-eicr-document-zika.xml"
* section[sliceRRSummarySection].extension.url = "http://hl7.org/fhir/us/ecr/StructureDefinition/rr-priority-extension"
* section[sliceRRSummarySection].extension.valueCodeableConcept = urn:oid:2.16.840.1.114222.4.5.274#RRVS17 "Immediate action required"
* section[sliceRRSummarySection].title = "Reportability Response Summary Section"
* section[sliceRRSummarySection].code = $loinc#55112-7 "Document summary"
* section[sliceRRSummarySection].text.status = #generated
* section[sliceRRSummarySection].text.div = "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>Summary:</b></p><p>Your organization electronically submitted an initial case report to determine if reporting to public health is needed for a patient. \"Zika virus disease (disorder)\" is reportable to \"State\r\n                    Department of Health\". An initial case report was sent to \"State Department of Health\". Additional information may be required for this report. <br/><br/></p><p><b>\"Zika virus disease (disorder)\" for \"State Department of Health\"</b></p><p>Reporting is required within \"24 hours\". Reporting to this Public Health Agency is based on \"both patient home address and provider facility address\". </p><ul><li><p>Local mosquito-borne Zika virus transmission was reported in your area. Increased watchfulness for symptoms of Zika virus in your patients is warranted. (Immediate action\r\n                            requested)</p></li><li><p>Additional information for the required reporting of Zika must be submitted to State Department of Health immediately. This additional information can be submitted here. ( <a href=\"http://statedepartmentofhealth.gov/epi/disease/zika/Supplemental_data_form.pdf\">Link</a> - Immediate action required) </p></li><li><p>Zika has particular risks for pregnant women. Follow-up guidance for pregnant women and couples who are planning pregnancy. ( <a href=\"http://statedepartmentofhealth.gov/epi/diseases/zika/Zika_Virus_Testing_Guidance.pdf\">Link</a> - Immediate action requested) </p></li><li><p>Further Laboratory testing for Zika may be needed. Guidance for additional testing and specimen collection ( <a href=\"http://statedepartmentofhealth.gov/epi/diseases/zika/Zika_Virus_Testing_Guidance.pdf\">Link</a> - Action requested) </p></li><li><p>Forms for submitting further Zika laboratory testing ( <a href=\"http://statedepartmentofhealth.gov/epi/diseases/zika/zika_test_request_form_UPHL.xlsx\">Link</a> - Information only)\r\n                        </p></li><li><p>Treatment guidance ( <a href=\"http://statedepartmentofhealth.gov/epi/diseases/zika/Zika_Virus_Testing_Guidance.pdf\">Link</a> - Information only) </p></li><li><p>If you have additional questions regarding Zika or reporting, contact information for the State Department of Health is available here. ( <a href=\"http://statedepartmentofhealth.gov/epi/diseases/zika/Zika_Virus_Testing_Guidance.pdf\">Link</a> - Information Only) </p></li></ul><p>Additional Resources (Information only):</p><ul><li><p>Control and prevention information for providers ( <a href=\"http://statedepartmentofhealth.gov/epi/diseases/zika/plan.pdf\">Link</a>) </p></li><li><p>Detailed condition references ( <a href=\"http://statedepartmentofhealth.gov/epi/diseases/zika/plan.pdf\">Link</a>) </p></li><li><p>Prevalence in State ( <a href=\"http://statedepartmentofhealth.gov/epi/diseases/zika/plan.pdf\">Link</a>) </p></li><li><p>CDC webpage ( <a href=\"https://www.cdc.gov/zika/index.html\">Link</a>) </p></li><li><p>Patient information factsheet ( <a href=\"http://statedepartmentofhealth.gov/epi/diseases/zika/factsheet.pdf\">Link</a>) </p></li><li><p>State Resident information ( <a href=\"http://statedepartmentofhealth.gov/epi/diseases/zika/ZikaVirus_QA_StateDOH.pdf\">Link</a>) </p></li></ul></div>"
* section[sliceRRSummarySection].entry[0].reference = "Observation/observation-rr-summary"
* section[sliceRRSummarySection].entry[=].display = "Reportability Response Summary"
* section[sliceRRSummarySection].entry[+].reference = "Observation/observation-rr-relevant-reportable-condition-observation"
* section[sliceRRSummarySection].entry[=].display = "Relevant reportable condition: Zika"