Instance: Inline-Instance-for-bundle-ecr-message-zika-2
InstanceOf: EICRDocumentBundle
Usage: #inline
* id = "bundle-eicr-document-zika"
* identifier.system = "urn:ietf:rfc:3986"
* identifier.value = "urn:uuid:2be4b4e4-6df1-4cb2-a947-c70fa0eda54b"
* type = #document
* timestamp = "2021-08-02T22:13:23Z"
* entry[0].fullUrl = "http://example.org/fhir/Composition/composition-eicr-zika"
* entry[=].resource.resourceType = "Composition"
* entry[=].resource.id = "composition-eicr-zika"
* entry[=].resource.meta.versionId = "22"
* entry[=].resource.meta.lastUpdated = "2021-08-17T03:24:45.575+00:00"
* entry[=].resource.meta.source = "#vMaRLlyzDNjGkVuc"
* entry[=].resource.meta.profile = "http://hl7.org/fhir/us/ecr/StructureDefinition/eicr-composition"
* entry[=].resource.extension.url = "http://hl7.org/fhir/StructureDefinition/composition-clinicaldocument-versionNumber"
* entry[=].resource.extension.valueString = "1"
* entry[=].resource.identifier.value = "c03eab8c-11e8-4d0c-ad2a-b385395e27db"
* entry[=].resource.status = #final
* entry[=].resource.type = $loinc#55751-2 "Public Health Case Report"
* entry[=].resource.subject.reference = "Patient/patient-ecr-eve-everywoman"
* entry[=].resource.subject.display = "Eve Everywoman"
* entry[=].resource.encounter.reference = "Encounter/encounter-eicr-eve-everywoman-outpatient"
* entry[=].resource.encounter.display = "Ambulatory Office Visit"
* entry[=].resource.date = "2018-01-02T22:13:23Z"
* entry[=].resource.author.reference = "PractitionerRole/practitionerrole-henry-seven"
* entry[=].resource.author.display = "Henry Seven, MD"
* entry[=].resource.title = "Initial Public Health Case Report - Zika Example"
* entry[=].resource.custodian.reference = "Organization/organization-ecr-salem-medical-center"
* entry[=].resource.custodian.display = "Salem Medical Center"
* entry[=].resource.section[0].title = "Reason for Visit Section"
* entry[=].resource.section[=].code = $loinc#29299-5 "Reason for visit Narrative"
* entry[=].resource.section[=].text.status = #generated
* entry[=].resource.section[=].text.div = "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table><tr><td style=\"font-weight: bold\">title</td><td><div title=\"title\">Reason for Visit Section</div></td></tr><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Reason for visit Narrative</div> ( <div title=\"code\">29299-5</div> ) </li><li><div title=\"system\"><a href=\"http://loinc.org\">http://loinc.org</a></div></li></ul></li></ul></td></tr><tr><td class=\"text-no-entries\" colspan=\"2\" lang=\"en-US\"><p>Reason for Visit: Bad cough</p></td></tr></table></div>"
* entry[=].resource.section[+].title = "Chief Complaint"
* entry[=].resource.section[=].code = $loinc#10154-3 "Chief complaint Narrative - Reported"
* entry[=].resource.section[=].text.status = #generated
* entry[=].resource.section[=].text.div = "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table><tr><td style=\"font-weight: bold\">title</td><td><div title=\"title\">Chief complaint Narrative - Reported</div></td></tr><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Chief complaint Narrative - Reported</div> ( <div title=\"code\">10154-3</div> ) </li><li><div title=\"system\"><a href=\"http://loinc.org\">http://loinc.org</a></div></li></ul></li></ul></td></tr><tr><td class=\"text-no-entries\" colspan=\"2\" lang=\"en-US\"><p>Chief Complaint: Bad cough</p></td></tr></table></div>"
* entry[=].resource.section[+].title = "History of Present Illness Section"
* entry[=].resource.section[=].code = $loinc#10164-2 "History of Present illness Narrative"
* entry[=].resource.section[=].text.status = #generated
* entry[=].resource.section[=].text.div = "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table><tr><td style=\"font-weight: bold\">title</td><td><div title=\"title\">History of Present Illness Section</div></td></tr><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">History of Present illness Narrative</div> ( <div title=\"code\">10164-2</div> ) </li><li><div title=\"system\"><a href=\"http://loinc.org\">http://loinc.org</a></div></li></ul></li></ul></td></tr><tr><td class=\"text-no-entries\" colspan=\"2\" lang=\"en-US\"> Persistent Cough REPORTED starting on 2018/03/05 <br/> Whooping Respiration not reported <br/> Paroxysms\r\n                                                    Of Coughing REPORTED starting on 2018/03/06 <br/> Post-tussive vomiting not reported </td></tr></table></div>"
* entry[=].resource.section[+].title = "Problems Section"
* entry[=].resource.section[=].code = $loinc#11450-4 "Problem list - Reported"
* entry[=].resource.section[=].text.status = #generated
* entry[=].resource.section[=].text.div = "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table><tr><td style=\"font-weight: bold\">title</td><td><div title=\"title\">Problems Section</div></td></tr><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Problem list - Reported</div> ( <div title=\"code\">11450-4</div> ) </li><li><div title=\"system\"><a href=\"http://loinc.org\">http://loinc.org</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">entry</td><td><a href=\"Condition-condition-eicr-eve-everywoman-common-cold.html\">Common cold (disorder)</a><table><tr><td style=\"font-weight: bold\">id</td><td><div title=\"id\">condition-eicr-eve-everywoman-common-cold</div></td></tr><tr><td style=\"font-weight: bold\">meta</td><td><table><tr><td style=\"font-weight: bold\">versionId</td><td><div title=\"versionId\">15</div></td></tr><tr><td style=\"font-weight: bold\">lastUpdated</td><td><div title=\"lastUpdated\">2019-10-10T21:21:49.000-04:00</div></td></tr><tr><td style=\"font-weight: bold\">profile</td><td><div title=\"profile\">http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-condition</div></td></tr></table></td></tr><tr><td style=\"font-weight: bold\">category</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Problem List Item</div> ( <div title=\"code\">problem-list-item</div> ) </li><li><div title=\"system\"><a href=\"http://terminology.hl7.org/CodeSystem/condition-category\">http://terminology.hl7.org/CodeSystem/condition-category</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Common cold (disorder)</div> ( <div title=\"code\">82272006</div> ) </li><li><div title=\"system\"><a href=\"http://snomed.info/sct\">http://snomed.info/sct</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">subject</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li/><li><a href=\"Patient-patient-ecr-eve-everywoman.html\">Eve Everywoman</a></li></ul></td></tr><tr><td style=\"font-weight: bold\">onsetDateTime</td><td><div title=\"onsetDateTime\">2017-09-23</div></td></tr><tr><td style=\"font-weight: bold\">asserter</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li/><li><a href=\"Practitioner-practitioner-us-core-henry-seven.html\">Henry Seven, MD</a></li></ul></td></tr></table></td></tr></table></div>"
* entry[=].resource.section[=].entry.reference = "Condition/condition-eicr-eve-everywoman-common-cold"
* entry[=].resource.section[=].entry.display = "Common cold (disorder)"
* entry[=].resource.section[+].title = "Medications Administered Section"
* entry[=].resource.section[=].code = $loinc#29549-3 "Medication administered Narrative"
* entry[=].resource.section[=].text.status = #generated
* entry[=].resource.section[=].text.div = "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table><tr><td style=\"font-weight: bold\">title</td><td><div title=\"title\">Medications Administered Section</div></td></tr><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Medication administered Narrative</div> ( <div title=\"code\">29549-3</div> ) </li><li><div title=\"system\"><a href=\"http://loinc.org\">http://loinc.org</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">entry</td><td><a href=\"MedicationAdministration-medicationadministration-eve-everywoman-azithromycin.html\">Azithromycin 500 MG Oral Tablet</a><table><tr><td style=\"font-weight: bold\">id</td><td><div title=\"id\">medicationadministration-eve-everywoman-azithromycin</div></td></tr><tr><td style=\"font-weight: bold\">meta</td><td><table><tr><td style=\"font-weight: bold\">versionId</td><td><div title=\"versionId\">10</div></td></tr><tr><td style=\"font-weight: bold\">lastUpdated</td><td><div title=\"lastUpdated\">2019-10-05T03:11:22.000-04:00</div></td></tr></table></td></tr><tr><td style=\"font-weight: bold\">status</td><td><div title=\"status\">completed</div></td></tr><tr><td style=\"font-weight: bold\">medicationCodeableConcept</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"text\">Azithromycin 500 MG Oral Tablet</div></li><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Azithromycin 500 MG Oral Tablet</div> ( <div title=\"code\">248656</div> ) </li><li><div title=\"system\"><a href=\"http://www.nlm.nih.gov/research/umls/rxnorm\">http://www.nlm.nih.gov/research/umls/rxnorm</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">subject</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li/><li><a href=\"Patient-patient-ecr-eve-everywoman.html\">Eve Everywoman</a></li></ul></td></tr><tr><td style=\"font-weight: bold\">effectivePeriod</td><td><table><tr><td style=\"font-weight: bold\">start</td><td><div title=\"start\">2018-03-07</div></td></tr><tr><td style=\"font-weight: bold\">end</td><td><div title=\"end\">2018-03-07</div></td></tr></table></td></tr><tr><td style=\"font-weight: bold\">dosage</td><td><table><tr><td style=\"font-weight: bold\">route</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Oral Route</div> ( <div title=\"code\">26643006</div> ) </li><li><div title=\"system\"><a href=\"http://snomed.info/sct\">http://snomed.info/sct</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">method</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Swallow - dosing instruction imperative (qualifier value)</div> ( <div title=\"code\">421521009</div> ) </li><li><div title=\"system\"><a href=\"http://snomed.info/sct\">http://snomed.info/sct</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">dose</td><td><table><tr><td style=\"font-weight: bold\">value</td><td><div title=\"value\">2</div></td></tr><tr><td style=\"font-weight: bold\">unit</td><td><div title=\"unit\">TAB</div></td></tr><tr><td style=\"font-weight: bold\">system</td><td><div title=\"system\"><a href=\"http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm\">http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm</a></div></td></tr><tr><td style=\"font-weight: bold\">code</td><td><div title=\"code\">TAB</div></td></tr></table></td></tr></table></td></tr></table></td></tr></table></div>"
* entry[=].resource.section[=].entry.reference = "MedicationAdministration/medicationadministration-eve-everywoman-azithromycin"
* entry[=].resource.section[=].entry.display = "Azithromycin 500 MG Oral Tablet"
* entry[=].resource.section[+].title = "Admission Medications Section"
* entry[=].resource.section[=].code = $loinc#42346-7 "Medications on admission (narrative)"
* entry[=].resource.section[=].text.status = #generated
* entry[=].resource.section[=].text.div = "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table><tr><td style=\"font-weight: bold\">title</td><td><div title=\"title\">Admission Medications Section</div></td></tr><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Medications on admission (narrative)</div> ( <div title=\"code\">42346-7</div> ) </li><li><div title=\"system\"><a href=\"http://loinc.org\">http://loinc.org</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">entry</td><td><a href=\"MedicationAdministration-medicationadministration-eve-everywoman-naloxone-response.html\">1 ML naloxone hydrochloride 0.4 MG/ML Injection</a></td></tr></table></div>"
* entry[=].resource.section[=].entry.reference = "MedicationAdministration/medicationadministration-eve-everywoman-naloxone-response"
* entry[=].resource.section[=].entry.display = "1 ML naloxone hydrochloride 0.4 MG/ML Injection"
* entry[=].resource.section[+].title = "Medications Section"
* entry[=].resource.section[=].code = $loinc#10160-0 "History of Medication use Narrative"
* entry[=].resource.section[=].text.status = #generated
* entry[=].resource.section[=].text.div = "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table><tr><td style=\"font-weight: bold\">title</td><td><div title=\"title\">Medications Section</div></td></tr><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">History of Medication use Narrative</div> ( <div title=\"code\">10160-0</div> ) </li><li><div title=\"system\"><a href=\"http://loinc.org\">http://loinc.org</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">entry</td><td><a href=\"MedicationAdministration-medicationadministration-eve-everywoman-azithromycin.html\">Azithromycin 500 MG Oral Tablet</a></td></tr></table></div>"
* entry[=].resource.section[=].entry.reference = "MedicationAdministration/medicationadministration-eve-everywoman-azithromycin"
* entry[=].resource.section[=].entry.display = "Azithromycin 500 MG Oral Tablet"
* entry[=].resource.section[+].title = "Results Section"
* entry[=].resource.section[=].code = $loinc#30954-2 "Relevant diagnostic tests/laboratory data note"
* entry[=].resource.section[=].text.status = #generated
* entry[=].resource.section[=].text.div = "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table><tr><td style=\"font-weight: bold\">title</td><td><div title=\"title\">Results Section</div></td></tr><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Relevant Dx tests/lab data</div> ( <div title=\"code\">30954-2</div> ) </li><li><div title=\"system\"><a href=\"http://loinc.org\">http://loinc.org</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">entry</td><td><a href=\"Observation-observation-us-ph-lab-result-eve-everywoman-lymphocytes.html\">Lymphocytes [#/​volume] in Blood by Automated count - Interpretation:\r\n                                                        High</a><table><tr><td style=\"font-weight: bold\">id</td><td><div title=\"id\">observation-us-ph-lab-result-eve-everywoman-lymphocytes</div></td></tr><tr><td style=\"font-weight: bold\">meta</td><td><table><tr><td style=\"font-weight: bold\">versionId</td><td><div title=\"versionId\">10</div></td></tr><tr><td style=\"font-weight: bold\">lastUpdated</td><td><div title=\"lastUpdated\">2019-10-05T02:50:13.000-04:00</div></td></tr><tr><td style=\"font-weight: bold\">profile</td><td><div title=\"profile\">http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-lab-result-observation</div></td></tr></table></td></tr><tr><td style=\"font-weight: bold\">status</td><td><div title=\"status\">final</div></td></tr><tr><td style=\"font-weight: bold\">category</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"text\">Laboratory</div></li><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Laboratory</div> ( <div title=\"code\">laboratory</div> ) </li><li><div title=\"system\"><a href=\"http://terminology.hl7.org/CodeSystem/observation-category\">http://terminology.hl7.org/CodeSystem/observation-category</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Lymphocytes [#/volume] in Blood by Automated count</div> ( <div title=\"code\">731-0</div> ) </li><li><div title=\"system\"><a href=\"http://loinc.org\">http://loinc.org</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">subject</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li/><li><a href=\"Patient-patient-ecr-eve-everywoman.html\">Eve Everywoman</a></li></ul></td></tr><tr><td style=\"font-weight: bold\">effectiveDateTime</td><td><div title=\"effectiveDateTime\">2018-03-07</div></td></tr><tr><td style=\"font-weight: bold\">valueQuantity</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"value\">5.2</div></li><li><div title=\"system\"><a href=\"http://unitsofmeasure.org\">http://unitsofmeasure.org</a></div></li><li><div title=\"code\">10*3/uL</div></li></ul></td></tr><tr><td style=\"font-weight: bold\">interpretation</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">High</div> ( <div title=\"code\">H</div> ) </li><li><div title=\"system\"><a href=\"http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation\">http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">referenceRange</td><td><table><tr><td style=\"font-weight: bold\">low</td><td><table><tr><td style=\"font-weight: bold\">value</td><td><div title=\"value\">1</div></td></tr><tr><td style=\"font-weight: bold\">system</td><td><div title=\"system\"><a href=\"http://unitsofmeasure.org\">http://unitsofmeasure.org</a></div></td></tr><tr><td style=\"font-weight: bold\">code</td><td><div title=\"code\">10*3/uL</div></td></tr></table></td></tr><tr><td style=\"font-weight: bold\">high</td><td><table><tr><td style=\"font-weight: bold\">value</td><td><div title=\"value\">4.8</div></td></tr><tr><td style=\"font-weight: bold\">system</td><td><div title=\"system\"><a href=\"http://unitsofmeasure.org\">http://unitsofmeasure.org</a></div></td></tr><tr><td style=\"font-weight: bold\">code</td><td><div title=\"code\">10*3/uL</div></td></tr></table></td></tr></table></td></tr></table></td></tr></table></div>"
* entry[=].resource.section[=].entry.reference = "Observation/observation-us-ph-lab-result-eve-everywoman-lymphocytes"
* entry[=].resource.section[=].entry.display = "Lymphocytes [#/​volume] in Blood by Automated count - Interpretation: High"
* entry[=].resource.section[+].title = "Plan of Treatment Section"
* entry[=].resource.section[=].code = $loinc#18776-5 "Plan of care note"
* entry[=].resource.section[=].text.status = #generated
* entry[=].resource.section[=].text.div = "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table><tr><td style=\"font-weight: bold\">title</td><td><div title=\"title\">Plan of Treatment Section</div></td></tr><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Plan of care note</div> ( <div title=\"code\">18776-5</div> ) </li><li><div title=\"system\"><a href=\"http://loinc.org\">http://loinc.org</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">entry</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><b>Trigger code</b></li><li>Trigger Code: </li><li>Trigger Code Display: </li><li>Trigger Code System: </li><li>Trigger Code Value Set: urn:oid:2.16.840.1.114222.4.11.7508</li><li>Trigger Code Value Set Version: 19/05/2018</li></ul><a href=\"ServiceRequest-servicerequest-eicr-zika.html\">Request for Zika virus envelope (E) gene [Presence] in Serum by Probe and target amplification\r\n                                                        method</a><table><tr><td style=\"font-weight: bold\">id</td><td><div title=\"id\">servicerequest-eicr-zika</div></td></tr><tr><td style=\"font-weight: bold\">meta</td><td><table><tr><td style=\"font-weight: bold\">versionId</td><td><div title=\"versionId\">9</div></td></tr><tr><td style=\"font-weight: bold\">lastUpdated</td><td><div title=\"lastUpdated\">2019-10-23T13:56:36.000-04:00</div></td></tr><tr><td style=\"font-weight: bold\">profile</td><td><div title=\"profile\">http://hl7.org/fhir/us/ecr/StructureDefinition/eicr-servicerequest</div></td></tr></table></td></tr><tr><td style=\"font-weight: bold\">status</td><td><div title=\"status\">completed</div></td></tr><tr><td style=\"font-weight: bold\">intent</td><td><div title=\"intent\">order</div></td></tr><tr><td style=\"font-weight: bold\">category</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"text\">Diagnostics Procedure</div></li><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Diagnostic procedure (procedure)</div> ( <div title=\"code\">103693007</div> ) </li><li><div title=\"system\"><a href=\"http://snomed.info/sct\">http://snomed.info/sct</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"text\">Zika RT-PCR</div></li><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Zika virus envelope E gene [Presence] in Serum by NAA with probe detection</div> ( <div title=\"code\">80825-3</div> ) </li><li><div title=\"system\"><a href=\"http://loinc.org\">http://loinc.org</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">subject</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li/><li><a href=\"Patient-patient-ecr-eve-everywoman.html\">Eve Everywoman</a></li></ul></td></tr><tr><td style=\"font-weight: bold\">performer</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li/><li><a href=\"Organization-organization-ecr-acme-laboratory.html\">Acme Labs</a></li></ul></td></tr></table></td></tr></table></div>"
* entry[=].resource.section[=].entry.extension.extension[0].url = "triggerCodeValueSet"
* entry[=].resource.section[=].entry.extension.extension[=].valueOid = "urn:oid:2.16.840.1.114222.4.11.7508"
* entry[=].resource.section[=].entry.extension.extension[+].url = "triggerCodeValueSetVersion"
* entry[=].resource.section[=].entry.extension.extension[=].valueString = "19/05/2018"
* entry[=].resource.section[=].entry.extension.extension[+].url = "triggerCode"
* entry[=].resource.section[=].entry.extension.extension[=].valueCoding = $loinc#80825-3 "Zika virus envelope E gene [Presence] in Serum by NAA with probe detection"
* entry[=].resource.section[=].entry.extension.url = "http://hl7.org/fhir/us/ecr/StructureDefinition/eicr-trigger-code-flag-extension"
* entry[=].resource.section[=].entry.reference = "ServiceRequest/servicerequest-eicr-zika"
* entry[=].resource.section[=].entry.display = "Request for Zika virus envelope (E) gene [Presence] in Serum by Probe and target amplification method"
* entry[=].resource.section[+].title = "Immunizations Section"
* entry[=].resource.section[=].code = $loinc#11369-6 "History of Immunization note"
* entry[=].resource.section[=].text.status = #generated
* entry[=].resource.section[=].text.div = "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table><tr><td style=\"font-weight: bold\">title</td><td><div title=\"title\">Immunizations Section</div></td></tr><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">History of Immunization note</div> ( <div title=\"code\">11369-6</div> ) </li><li><div title=\"system\"><a href=\"http://loinc.org\">http://loinc.org</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">entry</td><td><a href=\"Immunization-immunization-ecr-pneumo.html\">pneumococcal polysaccharide vaccine</a></td></tr><tr><td style=\"font-weight: bold\">entry</td><td><a href=\"Observation-observation-vaccine-credential-assertion-eve-everywoman.html\">Vaccine Credential Patient Assertion Observation Example</a></td></tr></table></div>"
* entry[=].resource.section[=].entry[0].reference = "Immunization/immunization-ecr-pneumo"
* entry[=].resource.section[=].entry[=].display = "pneumococcal polysaccharide vaccine"
* entry[=].resource.section[=].entry[+].reference = "Observation/observation-vaccine-credential-assertion-eve-everywoman"
* entry[=].resource.section[=].entry[=].display = "Vaccine Credential Patient Assertion Observation Example"
* entry[=].resource.section[+].title = "Procedures Section"
* entry[=].resource.section[=].code = $loinc#47519-4 "History of Procedures Document"
* entry[=].resource.section[=].text.status = #generated
* entry[=].resource.section[=].text.div = "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table><tr><td style=\"font-weight: bold\">title</td><td><div title=\"title\">Procedures Section</div></td></tr><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">History of Procedures Document</div> ( <div title=\"code\">47519-4</div> ) </li><li><div title=\"system\"><a href=\"http://loinc.org\">http://loinc.org</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">entry</td><td><a href=\"Procedure-us-ph-procedure-ecmo.html\">Extracorporeal membrane oxygenation (procedure)</a></td></tr></table></div>"
* entry[=].resource.section[=].entry.reference = "Procedure/us-ph-procedure-ecmo"
* entry[=].resource.section[=].entry.display = "Extracorporeal membrane oxygenation (procedure)"
* entry[=].resource.section[+].title = "Vital Signs Section"
* entry[=].resource.section[=].code = $loinc#8716-3 "Vital signs note"
* entry[=].resource.section[=].text.status = #generated
* entry[=].resource.section[=].text.div = "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table><tr><td style=\"font-weight: bold\">title</td><td><div title=\"title\">Vital Signs Section</div></td></tr><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Vital signs</div> ( <div title=\"code\">8716-3</div> ) </li><li><div title=\"system\"><a href=\"http://loinc.org\">http://loinc.org</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">entry</td><td><a href=\"Observation-observation-blood-pressure-eve-everywoman.html\">Blood pressure systolic and diastolic</a></td></tr></table></div>"
* entry[=].resource.section[=].entry.reference = "Observation/observation-blood-pressure-eve-everywoman"
* entry[=].resource.section[=].entry.display = "Blood pressure systolic and diastolic"
* entry[=].resource.section[+].title = "Social History Section"
* entry[=].resource.section[=].code = $loinc#29762-2 "Social history note"
* entry[=].resource.section[=].text.status = #generated
* entry[=].resource.section[=].text.div = "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table><tr><td style=\"font-weight: bold\">title</td><td><div title=\"title\">Social History Section</div></td></tr><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Social history note</div> ( <div title=\"code\">29762-2</div> ) </li><li><div title=\"system\"><a href=\"http://loinc.org\">http://loinc.org</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">entry</td><td><a href=\"Observation-observation-travel-history-eve-everywoman-201801.html\">eICR Travel History: Eve Everywoman 2018-01</a><table><tr><td style=\"font-weight: bold\">id</td><td><div title=\"id\">observation-travel-history-eve-everywoman-201801</div></td></tr><tr><td style=\"font-weight: bold\">meta</td><td><table><tr><td style=\"font-weight: bold\">versionId</td><td><div title=\"versionId\">11</div></td></tr><tr><td style=\"font-weight: bold\">lastUpdated</td><td><div title=\"lastUpdated\">2019-10-05T03:15:42.000-04:00</div></td></tr><tr><td style=\"font-weight: bold\">profile</td><td><div title=\"profile\">http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-travel-history</div></td></tr></table></td></tr><tr><td style=\"font-weight: bold\">status</td><td><div title=\"status\">final</div></td></tr><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"text\">Travel History</div></li><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Travel</div> ( <div title=\"code\">420008001</div> ) </li><li><div title=\"system\"><a href=\"http://snomed.info/sct\">http://snomed.info/sct</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">subject</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li/><li><a href=\"Patient-patient-ecr-eve-everywoman.html\">Eve Everywoman</a></li></ul></td></tr><tr><td style=\"font-weight: bold\">effectivePeriod</td><td><table><tr><td style=\"font-weight: bold\">start</td><td><div title=\"start\">2018-01-15</div></td></tr><tr><td style=\"font-weight: bold\">end</td><td><div title=\"end\">2018-01-30</div></td></tr></table></td></tr><tr><td style=\"font-weight: bold\">component</td><td><table><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Location</div> ( <div title=\"code\">LOC</div> ) </li><li><div title=\"system\"><a href=\"http://terminology.hl7.org/CodeSystem/v3-ParticipationType\">http://terminology.hl7.org/CodeSystem/v3-ParticipationType</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">valueCodeableConcept</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Fiji</div> ( <div title=\"code\">FJI</div> ) </li><li><div title=\"system\">urn:iso:std:iso:3166</div></li></ul></li></ul></td></tr></table></td></tr><tr><td style=\"font-weight: bold\">component</td><td><table><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Location</div> ( <div title=\"code\">LOC</div> ) </li><li><div title=\"system\"><a href=\"http://terminology.hl7.org/CodeSystem/v3-ParticipationType\">http://terminology.hl7.org/CodeSystem/v3-ParticipationType</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">valueCodeableConcept</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Vanuatu</div> ( <div title=\"code\">VUT</div> ) </li><li><div title=\"system\"><a href=\"https://phinvads.cdc.gov/vads/ViewCodeSystem.action?id=1.0.3166.1\">https://phinvads.cdc.gov/vads/ViewCodeSystem.action?id=1.0.3166.1</a></div></li></ul></li></ul></td></tr></table></td></tr></table></td></tr></table></div>"
* entry[=].resource.section[=].entry[0].reference = "Observation/observation-travel-history-eve-everywoman-201801"
* entry[=].resource.section[=].entry[=].display = "eICR Travel History: Eve Everywoman 2018-01"
* entry[=].resource.section[=].entry[+].reference = "Observation/observation-disability-status-eve-everywoman"
* entry[=].resource.section[=].entry[=].display = "US Public Health Disability Status Example"
* entry[=].resource.section[=].entry[+].reference = "Observation/observation-us-ph-exposure-contact-info-football-game"
* entry[=].resource.section[=].entry[=].display = "US Public Health Exposure Contact Information Example"
* entry[=].resource.section[=].entry[+].reference = "Observation/observation-country-of-nationality-eve-everywoman"
* entry[=].resource.section[=].entry[=].display = "Country of Nationality Observation Example"
* entry[=].resource.section[=].entry[+].reference = "Observation/observation-country-of-residence-eve-everywoman"
* entry[=].resource.section[=].entry[=].display = "Country of Residence Observation Example"
* entry[=].resource.section[+].title = "Pregnancy Section"
* entry[=].resource.section[=].code = $loinc#90767-5 "Pregnancy summary Document"
* entry[=].resource.section[=].text.status = #generated
* entry[=].resource.section[=].text.div = "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table><tr><td style=\"font-weight: bold\">title</td><td><div title=\"title\">Pregnancy Section</div></td></tr><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Pregnancy summary Document</div> ( <div title=\"code\">90767-5</div> ) </li><li><div title=\"system\"><a href=\"http://loinc.org\">http://loinc.org</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">entry</td><td><a href=\"Observation-observation-pregnancy-status-eve-everywoman.html\">eICR Pregnancy Status Example</a><table><tr><td style=\"font-weight: bold\">id</td><td><div title=\"id\">observation-pregnancy-status-eve-everywoman</div></td></tr><tr><td style=\"font-weight: bold\">meta</td><td><table><tr><td style=\"font-weight: bold\">versionId</td><td><div title=\"versionId\">13</div></td></tr><tr><td style=\"font-weight: bold\">lastUpdated</td><td><div title=\"lastUpdated\">2019-10-05T03:15:42.000-04:00</div></td></tr><tr><td style=\"font-weight: bold\">profile</td><td><div title=\"profile\">http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-pregnancy-status-observation</div></td></tr></table></td></tr><tr><td style=\"font-weight: bold\">us-ph-date-recorded-extension</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"valueDateTime\">2017-10-01</div></li></ul></td></tr><tr><td style=\"font-weight: bold\">date-determined-extension</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"valueDateTime\">2017-10-01</div></li></ul></td></tr><tr><td style=\"font-weight: bold\">status</td><td><div title=\"status\">final</div></td></tr><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Pregnancy Status</div> ( <div title=\"code\">82810-3</div> ) </li><li><div title=\"system\"><a href=\"http://loinc.org\">http://loinc.org</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">subject</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li/><li><a href=\"Patient-patient-ecr-eve-everywoman.html\">Eve Everywoman</a></li></ul></td></tr><tr><td style=\"font-weight: bold\">effectivePeriod</td><td><table><tr><td style=\"font-weight: bold\">start</td><td><div title=\"start\">2017-08-26</div></td></tr></table></td></tr><tr><td style=\"font-weight: bold\">valueCodeableConcept</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Pregnancy (finding)</div> ( <div title=\"code\">77386006</div> ) </li><li><div title=\"system\"><a href=\"http://snomed.info/sct\">http://snomed.info/sct</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">method</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Ultrasonography (procedure)</div> ( <div title=\"code\">16310003</div> ) </li><li><div title=\"system\"><a href=\"http://snomed.info/sct\">http://snomed.info/sct</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">component</td><td><table><tr><td style=\"font-weight: bold\">date-determined-extension</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"valueDateTime\">2017-10-01</div></li></ul></td></tr><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Gestational age Estimated from patient reported estimated date of conception</div> ( <div title=\"code\">53691-2</div> ) </li><li><div title=\"system\"><a href=\"http://loinc.org\">http://loinc.org</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">valueQuantity</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"value\">143</div></li><li><div title=\"unit\">d</div></li></ul></td></tr></table></td></tr><tr><td style=\"font-weight: bold\">component</td><td><table><tr><td style=\"font-weight: bold\">date-determined-extension</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"valueDateTime\">2017-10-01</div></li></ul></td></tr><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Delivery date Estimated from date fundal height reaches umb</div> ( <div title=\"code\">57064-8</div> ) </li><li><div title=\"system\"><a href=\"http://loinc.org\">http://loinc.org</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">valueDateTime</td><td><div title=\"valueDateTime\">2018-05-01</div></td></tr></table></td></tr></table></td></tr></table></div>"
* entry[=].resource.section[=].entry.reference = "Observation/observation-pregnancy-status-eve-everywoman"
* entry[=].resource.section[=].entry.display = "eICR Pregnancy Status Example"
* entry[=].resource.section[+].title = "Emergency Outbreak Information Section"
* entry[=].resource.section[=].code = $loinc#83910-0 "Public health Note"
* entry[=].resource.section[=].text.status = #generated
* entry[=].resource.section[=].text.div = "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table><tr><td style=\"font-weight: bold\">title</td><td><div title=\"title\">Emergency Outbreak Information Section</div></td></tr><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Public health Note</div> ( <div title=\"code\">83910-0</div> ) </li><li><div title=\"system\"><a href=\"http://loinc.org\">http://loinc.org</a></div></li></ul></li></ul></td></tr><tr><td style=\"font-weight: bold\">entry</td><td><a href=\"Observation-observation-us-ph-emergency-outbreak-info-eve-everywoman.html\">US Public Health Emergency Outbreak Information Example</a></td></tr></table></div>"
* entry[=].resource.section[=].entry.reference = "Observation/observation-us-ph-emergency-outbreak-info-eve-everywoman"
* entry[=].resource.section[=].entry.display = "US Public Health Emergency Outbreak Information Example"
* entry[=].resource.section[+].title = "Past Medical History Section"
* entry[=].resource.section[=].code = $loinc#11348-0 "History of Past illness note"
* entry[=].resource.section[=].text.status = #generated
* entry[=].resource.section[=].text.div = "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table><tr><td style=\"font-weight: bold\">title</td><td><div title=\"title\">Past Medical History Section</div></td></tr><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Past Medical History Narrative</div> ( <div title=\"code\">11348-0</div> ) </li><li><div title=\"system\"><a href=\"http://loinc.org\">http://loinc.org</a></div></li></ul></li></ul></td></tr><tr><td class=\"text-no-entries\" colspan=\"2\" lang=\"en-US\"><p>Past medical history</p></td></tr></table></div>"
* entry[=].resource.section[+].title = "Review of Systems Section"
* entry[=].resource.section[=].code = $loinc#10187-3 "Review of systems Narrative - Reported"
* entry[=].resource.section[=].text.status = #generated
* entry[=].resource.section[=].text.div = "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table><tr><td style=\"font-weight: bold\">title</td><td><div title=\"title\">Review of Systems Section</div></td></tr><tr><td style=\"font-weight: bold\">code</td><td><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><ul style=\"list-style:none; padding-left:0; margin:0 0;\"><li><div title=\"display\">Review of Systems Section Narrative</div> ( <div title=\"code\">10187-3</div> ) </li><li><div title=\"system\"><a href=\"http://loinc.org\">http://loinc.org</a></div></li></ul></li></ul></td></tr><tr><td class=\"text-no-entries\" colspan=\"2\" lang=\"en-US\"><p>Review of systems</p></td></tr></table></div>"
* entry[+].fullUrl = "http://example.org/fhir/MedicationAdministration/medicationadministration-eve-everywoman-azithromycin"
* entry[=].resource.resourceType = "MedicationAdministration"
* entry[=].resource.id = "medicationadministration-eve-everywoman-azithromycin"
* entry[=].resource.meta.versionId = "6"
* entry[=].resource.meta.lastUpdated = "2021-08-17T07:53:28.598+00:00"
* entry[=].resource.meta.source = "#O8n4DNqcDuNHPfTJ"
* entry[=].resource.meta.profile = "http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-medicationadministration"
* entry[=].resource.status = #completed
* entry[=].resource.medicationCodeableConcept = $rxnorm#248656 "Azithromycin 500 MG Oral Tablet"
* entry[=].resource.medicationCodeableConcept.text = "Azithromycin 500 MG Oral Tablet"
* entry[=].resource.subject.reference = "Patient/patient-ecr-eve-everywoman"
* entry[=].resource.subject.display = "Eve Everywoman"
* entry[=].resource.effectivePeriod.start = "2018-03-07"
* entry[=].resource.effectivePeriod.end = "2018-03-07"
* entry[=].resource.dosage.text = "Two tablets at once"
* entry[=].resource.dosage.route = $sct#26643006 "Oral route"
* entry[=].resource.dosage.method = $sct#421521009 "Swallow - dosing instruction imperative (qualifier value)"
* entry[=].resource.dosage.dose = 2 http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm#TAB "TAB"
* entry[+].fullUrl = "http://example.org/fhir/Procedure/us-ph-procedure-ecmo"
* entry[=].resource.resourceType = "Procedure"
* entry[=].resource.id = "us-ph-procedure-ecmo"
* entry[=].resource.meta.versionId = "5"
* entry[=].resource.meta.lastUpdated = "2021-06-28T08:12:56.829+00:00"
* entry[=].resource.meta.source = "#A9FdbPgUT95j7Itd"
* entry[=].resource.meta.profile = "http://hl7.org/fhir/us/ecr/StructureDefinition/eicr-procedure"
* entry[=].resource.identifier.system = "urn:ietf:rfc:3986"
* entry[=].resource.identifier.value = "urn:uuid:b2a737f2-2fdb-49c1-b097-dac173d07afd"
* entry[=].resource.status = #completed
* entry[=].resource.code = $sct#233573008 "Extracorporeal membrane oxygenation (procedure)"
* entry[=].resource.code.text = "Extracorporeal membrane oxygenation (procedure)"
* entry[=].resource.subject.reference = "Patient/patient-ecr-eve-everywoman"
* entry[=].resource.performedPeriod.start = "2020-11-01T12:55:26-07:00"
* entry[=].resource.performedPeriod.end = "2020-11-01T13:25:26-07:00"
* entry[=].resource.focalDevice.manipulated.reference = "Device/device-ecmo"
* entry[+].fullUrl = "http://example.org/fhir/MedicationAdministration/medicationadministration-eve-everywoman-naloxone-response"
* entry[=].resource.resourceType = "MedicationAdministration"
* entry[=].resource.id = "medicationadministration-eve-everywoman-naloxone-response"
* entry[=].resource.meta.versionId = "5"
* entry[=].resource.meta.lastUpdated = "2021-08-17T07:53:28.597+00:00"
* entry[=].resource.meta.source = "#5sOf7BOr595JpyG7"
* entry[=].resource.meta.profile = "http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-medicationadministration"
* entry[=].resource.extension.url = "http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-therapeutic-medication-response-extension"
* entry[=].resource.extension.valueCodeableConcept = $sct#268910001 "Patient's condition improved (finding)"
* entry[=].resource.status = #completed
* entry[=].resource.medicationCodeableConcept = $rxnorm#1659929 "1 ML naloxone hydrochloride 0.4 MG/ML Injection"
* entry[=].resource.subject.reference = "Patient/patient-ecr-eve-everywoman"
* entry[=].resource.subject.display = "Eve Everywoman"
* entry[=].resource.effectivePeriod.start = "2018-03-07"
* entry[=].resource.effectivePeriod.end = "2018-03-07"
* entry[=].resource.dosage.route = $sct#206007 "Gluteus maximus muscle"
* entry[=].resource.dosage.method = $sct#422145002 "Inject - dosing instruction imperative (qualifier value)"
* entry[=].resource.dosage.dose = 1 'mL' "mL"
* entry[+].fullUrl = "http://example.org/fhir/ServiceRequest/servicerequest-eicr-zika"
* entry[=].resource.resourceType = "ServiceRequest"
* entry[=].resource.id = "servicerequest-eicr-zika"
* entry[=].resource.meta.versionId = "5"
* entry[=].resource.meta.lastUpdated = "2021-08-17T08:02:21.928+00:00"
* entry[=].resource.meta.source = "#w4zRDqhjQ9EZHgCs"
* entry[=].resource.meta.profile = "http://hl7.org/fhir/us/ecr/StructureDefinition/eicr-servicerequest"
* entry[=].resource.identifier.system = "http://lab.smarthealthit.org"
* entry[=].resource.identifier.value = "061ef612-344f-4e7b-81a8-1059ae7bbe19"
* entry[=].resource.status = #completed
* entry[=].resource.intent = #order
* entry[=].resource.category = $sct#103693007 "Diagnostic procedure (procedure)"
* entry[=].resource.category.text = "Diagnostics Procedure"
* entry[=].resource.code = $loinc#80825-3 "Zika virus envelope E gene [Presence] in Serum by NAA with probe detection"
* entry[=].resource.code.text = "Zika RT-PCR"
* entry[=].resource.subject.reference = "Patient/patient-ecr-eve-everywoman"
* entry[=].resource.subject.display = "Eve Everywoman"
* entry[=].resource.performer.reference = "Organization/organization-ecr-acme-laboratory"
* entry[=].resource.performer.display = "Acme Labs"
* entry[+].fullUrl = "http://example.org/fhir/Condition/condition-eicr-eve-everywoman-common-cold"
* entry[=].resource.resourceType = "Condition"
* entry[=].resource.id = "condition-eicr-eve-everywoman-common-cold"
* entry[=].resource.meta.versionId = "6"
* entry[=].resource.meta.lastUpdated = "2021-07-15T01:54:14.831+00:00"
* entry[=].resource.meta.source = "#4g0ZpTNqldHFYLzr"
* entry[=].resource.meta.profile = "http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-condition"
* entry[=].resource.category = $condition-category#problem-list-item "Problem List Item"
* entry[=].resource.code = $sct#82272006 "Common cold (disorder)"
* entry[=].resource.subject.reference = "Patient/patient-ecr-eve-everywoman"
* entry[=].resource.subject.display = "Eve Everywoman"
* entry[=].resource.onsetDateTime = "2017-09-23"
* entry[=].resource.asserter.reference = "Practitioner/practitioner-us-core-henry-seven"
* entry[=].resource.asserter.display = "Henry Seven, MD"
* entry[+].fullUrl = "http://example.org/fhir/Encounter/encounter-eicr-eve-everywoman-outpatient"
* entry[=].resource.resourceType = "Encounter"
* entry[=].resource.id = "encounter-eicr-eve-everywoman-outpatient"
* entry[=].resource.meta.versionId = "5"
* entry[=].resource.meta.lastUpdated = "2021-07-19T03:02:05.806+00:00"
* entry[=].resource.meta.source = "#Q5dlT8eND2UI2D6e"
* entry[=].resource.meta.profile = "http://hl7.org/fhir/us/ecr/StructureDefinition/eicr-encounter"
* entry[=].resource.identifier.system = "http://hospital.smarthealthit.org"
* entry[=].resource.identifier.value = "9937012"
* entry[=].resource.status = #finished
* entry[=].resource.class = $v3-ActCode#AMB "ambulatory"
* entry[=].resource.type = $cpt#99202
* entry[=].resource.type.text = "Office Visit"
* entry[=].resource.subject.reference = "Patient/patient-ecr-eve-everywoman"
* entry[=].resource.subject.display = "Eve Everywoman"
* entry[=].resource.participant.type = $v3-ParticipationType#ATND "attender"
* entry[=].resource.participant.individual.reference = "PractitionerRole/practitionerrole-henry-seven"
* entry[=].resource.participant.individual.display = "Henry Seven, MD"
* entry[=].resource.period.start = "2018-04-01T10:00:00-05:00"
* entry[=].resource.period.end = "2018-04-02T10:15:00-05:00"
* entry[=].resource.diagnosis[0].extension.extension[0].url = "triggerCodeValueSet"
* entry[=].resource.diagnosis[=].extension.extension[=].valueOid = "urn:oid:2.16.840.1.114222.4.11.7508"
* entry[=].resource.diagnosis[=].extension.extension[+].url = "triggerCodeValueSetVersion"
* entry[=].resource.diagnosis[=].extension.extension[=].valueString = "12/12/2018"
* entry[=].resource.diagnosis[=].extension.extension[+].url = "triggerCode"
* entry[=].resource.diagnosis[=].extension.extension[=].valueCoding = $sct#3928002 "Zika virus disease (disorder)"
* entry[=].resource.diagnosis[=].extension.url = "http://hl7.org/fhir/us/ecr/StructureDefinition/eicr-trigger-code-flag-extension"
* entry[=].resource.diagnosis[=].condition.reference = "Condition/condition-eicr-eve-everywoman-zika"
* entry[=].resource.diagnosis[+].condition.reference = "Condition/condition-eicr-eve-everywoman-common-cold"
* entry[=].resource.location.location.reference = "Location/location-ecr-salem-medical-center"
* entry[=].resource.location.location.display = "Clinic Bldg A, Salem Medical Center, 4646 Brown Rd, Salem, MA 02368"
* entry[=].resource.serviceProvider.reference = "Organization/organization-ecr-salem-medical-center"
* entry[=].resource.serviceProvider.display = "Salem Medical Center, 22222 Health Authority Drive, Ann Arbor MI, 99999"
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-pregnancy-status-eve-everywoman"
* entry[=].resource.resourceType = "Observation"
* entry[=].resource.id = "observation-pregnancy-status-eve-everywoman"
* entry[=].resource.meta.versionId = "8"
* entry[=].resource.meta.lastUpdated = "2021-08-17T07:59:00.824+00:00"
* entry[=].resource.meta.source = "#bBlVx7OsNPsZVCbu"
* entry[=].resource.meta.profile = "http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-pregnancy-status-observation"
* entry[=].resource.extension[0].url = "http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-date-recorded-extension"
* entry[=].resource.extension[=].valueDateTime = "2017-10-01"
* entry[=].resource.extension[+].url = "http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-date-determined-extension"
* entry[=].resource.extension[=].valueDateTime = "2017-10-01"
* entry[=].resource.status = #final
* entry[=].resource.code = $loinc#82810-3 "Pregnancy status"
* entry[=].resource.subject.reference = "Patient/patient-ecr-eve-everywoman"
* entry[=].resource.subject.display = "Eve Everywoman"
* entry[=].resource.effectivePeriod.start = "2017-08-26"
* entry[=].resource.valueCodeableConcept = $sct#77386006 "Pregnancy (finding)"
* entry[=].resource.method = $sct#16310003 "Ultrasonography (procedure)"
* entry[=].resource.component[0].extension.url = "http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-date-determined-extension"
* entry[=].resource.component[=].extension.valueDateTime = "2017-10-01"
* entry[=].resource.component[=].code = $loinc#53691-2 "Gestational age Estimated from patient reported estimated date of conception"
* entry[=].resource.component[=].valueQuantity.value = 143
* entry[=].resource.component[=].valueQuantity.unit = "d"
* entry[=].resource.component[+].extension.url = "http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-date-determined-extension"
* entry[=].resource.component[=].extension.valueDateTime = "2017-10-01"
* entry[=].resource.component[=].code = $loinc#57064-8 "Delivery date Estimated from date fundal height reaches umb"
* entry[=].resource.component[=].valueDateTime = "2018-05-01"
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-vaccine-credential-assertion-eve-everywoman"
* entry[=].resource.resourceType = "Observation"
* entry[=].resource.id = "observation-vaccine-credential-assertion-eve-everywoman"
* entry[=].resource.meta.versionId = "2"
* entry[=].resource.meta.lastUpdated = "2021-08-13T04:25:18.607+00:00"
* entry[=].resource.meta.source = "#12yO2DqhRxbXmEOy"
* entry[=].resource.meta.profile = "http://hl7.org/fhir/us/ecr/StructureDefinition/eicr-vaccine-credential-patient-assertion"
* entry[=].resource.status = #final
* entry[=].resource.code = $loinc#11370-4 "Immunization status - Reported"
* entry[=].resource.subject.reference = "Patient/patient-ecr-eve-everywoman"
* entry[=].resource.subject.display = "Eve Everywoman"
* entry[=].resource.effectiveDateTime = "2020-11-10T22:33:22Z"
* entry[=].resource.valueCodeableConcept = $v2-0532#Y "Yes"
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-us-ph-emergency-outbreak-info-eve-everywoman"
* entry[=].resource.resourceType = "Observation"
* entry[=].resource.id = "observation-us-ph-emergency-outbreak-info-eve-everywoman"
* entry[=].resource.meta.versionId = "4"
* entry[=].resource.meta.lastUpdated = "2021-07-15T01:22:52.178+00:00"
* entry[=].resource.meta.source = "#oAXhG2HyvbL70uEB"
* entry[=].resource.meta.profile = "http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-emergency-outbreak-information"
* entry[=].resource.status = #final
* entry[=].resource.code.text = "Employee desk distance from mail sorter"
* entry[=].resource.subject.reference = "Patient/patient-ecr-eve-everywoman"
* entry[=].resource.subject.display = "Eve Everywoman"
* entry[=].resource.effectiveDateTime = "2020-11-18T22:33:22Z"
* entry[=].resource.valueQuantity.value = 2
* entry[=].resource.valueQuantity.unit = "m"
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-country-of-nationality-eve-everywoman"
* entry[=].resource.resourceType = "Observation"
* entry[=].resource.id = "observation-country-of-nationality-eve-everywoman"
* entry[=].resource.meta.versionId = "1"
* entry[=].resource.meta.lastUpdated = "2021-08-19T21:30:49.456+00:00"
* entry[=].resource.meta.source = "#ABFWLRjmURVC23y1"
* entry[=].resource.meta.profile = "http://hl7.org/fhir/us/ecr/StructureDefinition/eicr-country-of-nationality"
* entry[=].resource.status = #final
* entry[=].resource.code = $sct#186034007 "Ethnicity / related nationality data (observable entity)"
* entry[=].resource.subject.reference = "Patient/patient-ecr-eve-everywoman"
* entry[=].resource.subject.display = "Eve Everywoman"
* entry[=].resource.effectiveDateTime = "2020-11-10T22:33:22Z"
* entry[=].resource.valueCodeableConcept = urn:iso:std:iso:3166#AU "Australia"
* entry[+].fullUrl = "http://example.org/fhir/Patient/patient-ecr-eve-everywoman"
* entry[=].resource.resourceType = "Patient"
* entry[=].resource.id = "patient-ecr-eve-everywoman"
* entry[=].resource.meta.versionId = "10"
* entry[=].resource.meta.lastUpdated = "2021-08-17T08:00:32.356+00:00"
* entry[=].resource.meta.source = "#zjFlzHDvZIYVyMAB"
* entry[=].resource.meta.profile = "http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-patient"
* entry[=].resource.text.status = #generated
* entry[=].resource.text.div = "<div xmlns=\"http://www.w3.org/1999/xhtml\"><div class=\"hapiHeaderText\">Eve L <b>EVERYWOMAN </b></div><table class=\"hapiPropertyTable\"><tbody><tr><td>Identifier</td><td>1032702</td></tr><tr><td>Address</td><td><span>5101 Peachtree St NE </span><br/><span>Atlanta </span><span>GA </span><span>US </span></td></tr><tr><td>Date of birth</td><td><span>24 November 1974</span></td></tr></tbody></table></div>"
* entry[=].resource.extension[0].extension[0].url = "ombCategory"
* entry[=].resource.extension[=].extension[=].valueCoding = urn:oid:2.16.840.1.113883.6.238#2106-3 "White"
* entry[=].resource.extension[=].extension[+].url = "text"
* entry[=].resource.extension[=].extension[=].valueString = "White"
* entry[=].resource.extension[=].url = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race"
* entry[=].resource.extension[+].extension[0].url = "ombCategory"
* entry[=].resource.extension[=].extension[=].valueCoding = urn:oid:2.16.840.1.113883.6.238#2186-5 "Not Hispanic or Latino"
* entry[=].resource.extension[=].extension[+].url = "text"
* entry[=].resource.extension[=].extension[=].valueString = "Not Hispanic or Latino"
* entry[=].resource.extension[=].url = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity"
* entry[=].resource.extension[+].url = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex"
* entry[=].resource.extension[=].valueCode = #F
* entry[=].resource.extension[+].extension.url = "value"
* entry[=].resource.extension[=].extension.valueCodeableConcept = $v3-NullFlavor#ASKU "asked but unknown"
* entry[=].resource.extension[=].extension.valueCodeableConcept.text = "asked but unknown"
* entry[=].resource.extension[=].url = "http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-genderidentity-extension"
* entry[=].resource.extension[+].extension[0].url = "TribeName"
* entry[=].resource.extension[=].extension[=].valueCoding = $v3-TribalEntityUS#91 "Fort Mojave Indian Tribe of Arizona, California & Nevada"
* entry[=].resource.extension[=].extension[+].url = "EnrolledTribeMember"
* entry[=].resource.extension[=].extension[=].valueBoolean = true
* entry[=].resource.extension[=].url = "http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-tribal-affiliation-extension"
* entry[=].resource.identifier.use = #usual
* entry[=].resource.identifier.type = $v2-0203#MR "Medical Record Number"
* entry[=].resource.identifier.system = "http://hospital.smarthealthit.org"
* entry[=].resource.identifier.value = "1032702"
* entry[=].resource.active = true
* entry[=].resource.name.family = "Everywoman"
* entry[=].resource.name.given[0] = "Eve"
* entry[=].resource.name.given[+] = "L"
* entry[=].resource.telecom[0].system = #phone
* entry[=].resource.telecom[=].value = "1-(404)555-1212"
* entry[=].resource.telecom[=].use = #home
* entry[=].resource.telecom[+].system = #email
* entry[=].resource.telecom[=].value = "eve.everywoman@example.com"
* entry[=].resource.gender = #female
* entry[=].resource.birthDate = "1974-11-24"
* entry[=].resource.deceasedBoolean = false
* entry[=].resource.address.line = "5101 Peachtree St NE"
* entry[=].resource.address.city = "Atlanta"
* entry[=].resource.address.state = "GA"
* entry[=].resource.address.postalCode = "30302"
* entry[=].resource.address.country = "US"
* entry[=].resource.communication.language = urn:ietf:bcp:47#en "English"
* entry[+].fullUrl = "http://example.org/fhir/Immunization/immunization-ecr-pneumo"
* entry[=].resource.resourceType = "Immunization"
* entry[=].resource.id = "immunization-ecr-pneumo"
* entry[=].resource.meta.versionId = "8"
* entry[=].resource.meta.lastUpdated = "2021-08-17T07:51:35.117+00:00"
* entry[=].resource.meta.source = "#EdjaILZHXKHi4bdN"
* entry[=].resource.meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-immunization"
* entry[=].resource.status = #completed
* entry[=].resource.vaccineCode = $cvx#33 "pneumococcal polysaccharide PPV23"
* entry[=].resource.patient.reference = "Patient/patient-ecr-eve-everywoman"
* entry[=].resource.patient.display = "Eve Everywoman"
* entry[=].resource.occurrenceDateTime = "2018-09-01"
* entry[=].resource.primarySource = true
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-country-of-residence-eve-everywoman"
* entry[=].resource.resourceType = "Observation"
* entry[=].resource.id = "observation-country-of-residence-eve-everywoman"
* entry[=].resource.meta.versionId = "1"
* entry[=].resource.meta.lastUpdated = "2021-08-13T00:20:14.025+00:00"
* entry[=].resource.meta.source = "#HDoLJzr0kfWKFp3F"
* entry[=].resource.meta.profile = "http://hl7.org/fhir/us/ecr/StructureDefinition/eicr-country-of-residence"
* entry[=].resource.status = #final
* entry[=].resource.code = $loinc#77983-5 "Country of usual residence"
* entry[=].resource.subject.reference = "Patient/patient-ecr-eve-everywoman"
* entry[=].resource.subject.display = "Eve Everywoman"
* entry[=].resource.effectiveDateTime = "2020-11-10T22:33:22Z"
* entry[=].resource.valueCodeableConcept = urn:iso:std:iso:3166#GB "United Kingdom of Great Britain and Northern Ireland (the)"
* entry[+].fullUrl = "http://example.org/fhir/PractitionerRole/practitionerrole-henry-seven"
* entry[=].resource.resourceType = "PractitionerRole"
* entry[=].resource.id = "practitionerrole-henry-seven"
* entry[=].resource.meta.versionId = "11"
* entry[=].resource.meta.lastUpdated = "2021-08-17T08:00:32.355+00:00"
* entry[=].resource.meta.source = "#KJ942UxvfdYWoHCF"
* entry[=].resource.meta.profile = "http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-practitionerrole"
* entry[=].resource.identifier.system = "http://hl7.org/fhir/sid/us-npi"
* entry[=].resource.identifier.value = "9941339108"
* entry[=].resource.practitioner.reference = "Practitioner/practitioner-us-core-henry-seven"
* entry[=].resource.practitioner.display = "Henry Seven, MD"
* entry[=].resource.organization.reference = "Organization/organization-ecr-salem-medical-center"
* entry[=].resource.organization.display = "Salem Medical Center"
* entry[=].resource.code = $provider-taxonomy#261QP2300X "Primary Care Clinic/Center"
* entry[=].resource.specialty = $sct#419772000 "Family practice"
* entry[=].resource.location.reference = "Location/location-ecr-salem-medical-center"
* entry[=].resource.location.display = "Salem Medical Center"
* entry[=].resource.telecom.system = #email
* entry[=].resource.telecom.value = "henry.seven@example.com"
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-blood-pressure-eve-everywoman"
* entry[=].resource.resourceType = "Observation"
* entry[=].resource.id = "observation-blood-pressure-eve-everywoman"
* entry[=].resource.meta.versionId = "2"
* entry[=].resource.meta.lastUpdated = "2021-07-19T08:19:31.753+00:00"
* entry[=].resource.meta.source = "#2PjceWUbU0gCYVZA"
* entry[=].resource.meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-blood-pressure"
* entry[=].resource.status = #final
* entry[=].resource.category = $observation-category#vital-signs "Vital Signs"
* entry[=].resource.category.text = "Vital Signs"
* entry[=].resource.code = $loinc#85354-9 "Blood pressure panel with all children optional"
* entry[=].resource.code.text = "Blood pressure systolic and diastolic"
* entry[=].resource.subject.reference = "Patient/patient-ecr-eve-everywoman"
* entry[=].resource.subject.display = "Eve Everywoman"
* entry[=].resource.encounter.display = "GP Visit"
* entry[=].resource.effectiveDateTime = "2020-07-02"
* entry[=].resource.component[0].code = $loinc#8480-6 "Systolic blood pressure"
* entry[=].resource.component[=].code.text = "Systolic blood pressure"
* entry[=].resource.component[=].valueQuantity = 109 'mm[Hg]' "mmHg"
* entry[=].resource.component[+].code = $loinc#8462-4 "Diastolic blood pressure"
* entry[=].resource.component[=].code.text = "Diastolic blood pressure"
* entry[=].resource.component[=].valueQuantity = 44 'mm[Hg]' "mmHg"
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-us-ph-exposure-contact-info-football-game"
* entry[=].resource.resourceType = "Observation"
* entry[=].resource.id = "observation-us-ph-exposure-contact-info-football-game"
* entry[=].resource.meta.versionId = "4"
* entry[=].resource.meta.lastUpdated = "2020-12-01T07:17:32.073+00:00"
* entry[=].resource.meta.source = "#pMvWUdCWz4XOnrDf"
* entry[=].resource.meta.profile = "http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-exposure-contact-information"
* entry[=].resource.status = #final
* entry[=].resource.category = $v3-ActClass#EXPOS "exposure"
* entry[=].resource.category.text = "An interaction between entities that provides opportunity for transmission of a physical, chemical, or biological agent from an exposure source entity to an exposure target entity."
* entry[=].resource.code = $umls#C3841750 "Mass gathering"
* entry[=].resource.code.text = "Mass gathering (football game)"
* entry[=].resource.subject.reference = "Patient/patient-ecr-eve-everywoman"
* entry[=].resource.subject.display = "Eve Everywoman"
* entry[=].resource.focus.reference = "Location/location-ecr-city-football-stadium"
* entry[=].resource.focus.display = "City Football Stadium"
* entry[=].resource.effectivePeriod.start = "2020-01-11T18:00:00Z"
* entry[=].resource.effectivePeriod.end = "2020-01-11T21:30:00Z"
* entry[=].resource.valueCodeableConcept = $sct#264379009 "Sports stadium (environment)"
* entry[=].resource.valueCodeableConcept.text = "City Football Stadium"
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-travel-history-eve-everywoman-201801"
* entry[=].resource.resourceType = "Observation"
* entry[=].resource.id = "observation-travel-history-eve-everywoman-201801"
* entry[=].resource.meta.versionId = "9"
* entry[=].resource.meta.lastUpdated = "2021-08-17T07:59:01.126+00:00"
* entry[=].resource.meta.source = "#d6PrWfFFuxUIiLtX"
* entry[=].resource.meta.profile = "http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-travel-history"
* entry[=].resource.status = #final
* entry[=].resource.code = $sct#420008001 "Travel"
* entry[=].resource.code.text = "Travel History"
* entry[=].resource.subject.reference = "Patient/patient-ecr-eve-everywoman"
* entry[=].resource.subject.display = "Eve Everywoman"
* entry[=].resource.effectivePeriod.start = "2018-01-15"
* entry[=].resource.effectivePeriod.end = "2018-01-30"
* entry[=].resource.component[0].code = $v3-ParticipationType#LOC "Location"
* entry[=].resource.component[=].valueCodeableConcept = urn:iso:std:iso:3166#FJI "Fiji"
* entry[=].resource.component[+].code = $v3-ParticipationType#LOC "Location"
* entry[=].resource.component[=].valueCodeableConcept = urn:oid:1.0.3166.1#VUT "Vanuatu"
* entry[=].resource.component[+].code = $sct#280147009 "Type of activity (attribute)"
* entry[=].resource.component[=].valueCodeableConcept = $sct#702348006 "Active duty military (occupation)"
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-disability-status-eve-everywoman"
* entry[=].resource.resourceType = "Observation"
* entry[=].resource.id = "observation-disability-status-eve-everywoman"
* entry[=].resource.meta.versionId = "2"
* entry[=].resource.meta.lastUpdated = "2021-06-30T05:33:12.487+00:00"
* entry[=].resource.meta.source = "#AVCvf6gXu6hyNuWr"
* entry[=].resource.meta.profile = "http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-disability-status"
* entry[=].resource.status = #final
* entry[=].resource.code = $loinc#69856-3 "Are you deaf, or do you have serious difficulty hearing"
* entry[=].resource.subject.reference = "Patient/patient-ecr-eve-everywoman"
* entry[=].resource.subject.display = "Eve Everywoman"
* entry[=].resource.effectiveDateTime = "2020-11-10T22:33:22Z"
* entry[=].resource.valueBoolean = true
* entry[+].fullUrl = "http://example.org/fhir/Observation/observation-us-ph-lab-result-eve-everywoman-lymphocytes"
* entry[=].resource.resourceType = "Observation"
* entry[=].resource.id = "observation-us-ph-lab-result-eve-everywoman-lymphocytes"
* entry[=].resource.meta.profile = "http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-lab-result-observation"
* entry[=].resource.status = #final
* entry[=].resource.category = $observation-category#laboratory "Laboratory"
* entry[=].resource.category.text = "Laboratory"
* entry[=].resource.code = $loinc#731-0 "Lymphocytes [#/volume] in Blood by Automated count"
* entry[=].resource.subject.reference = "Patient/patient-ecr-eve-everywoman"
* entry[=].resource.subject.display = "Eve Everywoman"
* entry[=].resource.effectiveDateTime = "2018-03-07"
* entry[=].resource.valueQuantity = 5.2 '10*3/uL'
* entry[=].resource.interpretation = $v3-ObservationInterpretation#H "High"
* entry[=].resource.referenceRange.low = 1 '10*3/uL'
* entry[=].resource.referenceRange.high = 4.8 '10*3/uL'
* entry[+].fullUrl = "http://example.org/fhir/Organization/organization-ecr-acme-laboratory"
* entry[=].resource.resourceType = "Organization"
* entry[=].resource.id = "organization-ecr-acme-laboratory"
* entry[=].resource.meta.versionId = "4"
* entry[=].resource.meta.lastUpdated = "2021-06-30T04:13:19.329+00:00"
* entry[=].resource.meta.source = "#xp7CXcY2lPaNsDQL"
* entry[=].resource.meta.profile = "http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-organization"
* entry[=].resource.identifier.system = "http://hl7.org.fhir/sid/us-npi"
* entry[=].resource.identifier.value = "1144221999"
* entry[=].resource.active = true
* entry[=].resource.type = $v3-RoleCode#OUTLAB "outpatient laboratory"
* entry[=].resource.name = "Acme_Labs"
* entry[=].resource.telecom[0].system = #phone
* entry[=].resource.telecom[=].value = "+1-555-555-4444"
* entry[=].resource.telecom[+].system = #email
* entry[=].resource.telecom[=].value = "mail@acme-labs.com"
* entry[=].resource.address.line = "7777 Laboratory Drive"
* entry[=].resource.address.city = "Ann Arbor"
* entry[=].resource.address.state = "MI"
* entry[=].resource.address.postalCode = "99999"
* entry[+].fullUrl = "http://example.org/fhir/Location/location-ecr-salem-medical-center"
* entry[=].resource.resourceType = "Location"
* entry[=].resource.id = "location-ecr-salem-medical-center"
* entry[=].resource.meta.versionId = "6"
* entry[=].resource.meta.lastUpdated = "2021-08-17T07:53:02.099+00:00"
* entry[=].resource.meta.source = "#VI2Nm5Ps5HqZ5HXV"
* entry[=].resource.meta.profile = "http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-location"
* entry[=].resource.identifier.system = "http://hl7.org.fhir/sid/us-npi"
* entry[=].resource.identifier.value = "1144221995"
* entry[=].resource.status = #active
* entry[=].resource.name = "Clinic Bldg A, Salem Medical Center"
* entry[=].resource.type = $v3-RoleCode#HOSP "Hospital"
* entry[=].resource.telecom[0].system = #phone
* entry[=].resource.telecom[=].value = "(+1) (555)555-3001"
* entry[=].resource.telecom[+].system = #fax
* entry[=].resource.telecom[=].value = "(+1) (555)555-3002"
* entry[=].resource.telecom[+].system = #email
* entry[=].resource.telecom[=].value = "mail@smc.org"
* entry[=].resource.address.line[0] = "Clinic Bldg A"
* entry[=].resource.address.line[+] = "4444 Healthcare Drive"
* entry[=].resource.address.city = "Ann Arbor"
* entry[=].resource.address.state = "MI"
* entry[=].resource.address.postalCode = "99999"
* entry[=].resource.managingOrganization.reference = "Organization/organization-ecr-salem-medical-center"
* entry[+].fullUrl = "http://example.org/fhir/Location/location-ecr-city-football-stadium"
* entry[=].resource.resourceType = "Location"
* entry[=].resource.id = "location-ecr-city-football-stadium"
* entry[=].resource.meta.versionId = "1"
* entry[=].resource.meta.lastUpdated = "2020-12-01T01:55:32.705+00:00"
* entry[=].resource.meta.source = "#KLUFk4w6CXKqrFEC"
* entry[=].resource.meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-location"
* entry[=].resource.status = #active
* entry[=].resource.name = "City Football Stadium"
* entry[=].resource.type = $sct#264379009 "Sports stadium (environment)"
* entry[=].resource.type.text = "City Football Stadium"
* entry[=].resource.address.line = "99 Football Stadium Road"
* entry[=].resource.address.city = "My City"
* entry[=].resource.address.state = "AZ"
* entry[=].resource.address.postalCode = "8562"
* entry[+].fullUrl = "http://example.org/fhir/Organization/organization-ecr-salem-medical-center"
* entry[=].resource.resourceType = "Organization"
* entry[=].resource.id = "organization-ecr-salem-medical-center"
* entry[=].resource.meta.versionId = "5"
* entry[=].resource.meta.lastUpdated = "2021-06-30T04:13:19.345+00:00"
* entry[=].resource.meta.source = "#xa4yJZjn68xVavoM"
* entry[=].resource.meta.profile = "http://hl7.org/fhir/us/ecr/StructureDefinition/us-ph-organization"
* entry[=].resource.identifier.system = "http://hl7.org.fhir/sid/us-npi"
* entry[=].resource.identifier.value = "55555555"
* entry[=].resource.active = true
* entry[=].resource.name = "Salem Medical Center"
* entry[=].resource.telecom[0].system = #phone
* entry[=].resource.telecom[=].value = "+1-555-555-1111"
* entry[=].resource.telecom[+].system = #email
* entry[=].resource.telecom[=].value = "mail@salemmedicalcenter.com"
* entry[=].resource.address.line = "22222 Health Authority Drive"
* entry[=].resource.address.city = "Ann Arbor"
* entry[=].resource.address.state = "MI"
* entry[=].resource.address.postalCode = "99999"
* entry[+].fullUrl = "http://example.org/fhir/Condition/condition-eicr-eve-everywoman-zika"
* entry[=].resource.resourceType = "Condition"
* entry[=].resource.id = "condition-eicr-eve-everywoman-zika"
* entry[=].resource.meta.versionId = "5"
* entry[=].resource.meta.lastUpdated = "2021-07-15T01:54:14.835+00:00"
* entry[=].resource.meta.source = "#rM2Pw6getjoE2UTV"
* entry[=].resource.category = $condition-category#encounter-diagnosis "Encounter Diagnosis"
* entry[=].resource.code = $sct#3928002 "Zika virus disease (disorder)"
* entry[=].resource.subject.reference = "Patient/patient-ecr-eve-everywoman"
* entry[=].resource.subject.display = "Eve Everywoman"
* entry[=].resource.onsetDateTime = "2017-08-23"
* entry[=].resource.asserter.reference = "Practitioner/practitioner-us-core-henry-seven"
* entry[=].resource.asserter.display = "Henry Seven, MD"
* entry[+].fullUrl = "http://example.org/fhir/Practitioner/practitioner-us-core-henry-seven"
* entry[=].resource.resourceType = "Practitioner"
* entry[=].resource.id = "practitioner-us-core-henry-seven"
* entry[=].resource.meta.versionId = "5"
* entry[=].resource.meta.lastUpdated = "2021-08-17T08:00:32.356+00:00"
* entry[=].resource.meta.source = "#2MfA6kIjmOmtAlIb"
* entry[=].resource.meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-practitioner"
* entry[=].resource.identifier.system = "http://hl7.org/fhir/sid/us-npi"
* entry[=].resource.identifier.value = "9941339108"
* entry[=].resource.name.family = "Henry"
* entry[=].resource.name.given = "Seven"
* entry[=].resource.name.suffix = "M.D."
* entry[=].resource.telecom.system = #email
* entry[=].resource.telecom.value = "henry.seven@example.com"
* entry[=].resource.address.line[0] = "BMass Doctors"
* entry[=].resource.address.line[+] = "2100 North Ave"
* entry[=].resource.address.city = "Burlington"
* entry[=].resource.address.state = "MA"
* entry[=].resource.address.postalCode = "02368"
* entry[=].resource.address.country = "US"
* entry[+].fullUrl = "http://example.org/fhir/Device/device-ecmo"
* entry[=].resource.resourceType = "Device"
* entry[=].resource.id = "device-ecmo"
* entry[=].resource.meta.versionId = "3"
* entry[=].resource.meta.lastUpdated = "2021-06-30T07:22:44.658+00:00"
* entry[=].resource.meta.source = "#WUV2SWqz3ej775gd"
* entry[=].resource.text.status = #generated
* entry[=].resource.text.div = "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>Manually Created Narrative</b></p><h3>UDI</h3><p><b>Device Identifier</b>: 99863313444317 </p><p><b>CarrierHRF</b>: (01)99863313444316(17)220101(10)M320(21)AC222 </p><p><b>EntryType</b>: rfid </p><p><b>Name</b>: ACME Extracorporeal membrane oxygenator </p><p><b>Type</b>: udi-label-name </p><p><b>status</b>: active </p><p><b>manufacturer</b>: ACME Biomedical </p><p><b>expirationDate</b>: 2024-01-01 </p><p><b>lotNumber</b>: M321 </p><p><b>serialNumber</b>: AC222 </p><p><b>modelNumber</b>: 4.0 </p><p><b>patient</b>: <a href=\"Patient-patient-ecr-eve-everywoman.html\">Eve Everywoman. Generated Summary: Medical Record Number: 1032702 (USUAL); active; Eve L Everywoman ;\r\n                                            Phone: 1-(404)555-1212, eve.everywoman@example.com; gender: female; birthDate: 1974-11-24</a></p></div>"
* entry[=].resource.udiCarrier.deviceIdentifier = "99863313444316"
* entry[=].resource.udiCarrier.carrierHRF = "(01)99863313444316(17)220101(10)M320(21)AC222"
* entry[=].resource.udiCarrier.entryType = #rfid
* entry[=].resource.status = #active
* entry[=].resource.manufacturer = "ACME Biomedical"
* entry[=].resource.expirationDate = "2022-01-01"
* entry[=].resource.lotNumber = "M320"
* entry[=].resource.serialNumber = "AC222"
* entry[=].resource.deviceName.name = "ACME Extracorporeal membrane oxygenator"
* entry[=].resource.deviceName.type = #udi-label-name
* entry[=].resource.modelNumber = "4.0"
* entry[=].resource.type = $sct#469244005 "Extracorporeal membrane oxygenator (physical object)"
* entry[=].resource.type.text = "Extracorporeal membrane oxygenator (physical object)"
* entry[=].resource.patient.reference = "Patient/patient-ecr-eve-everywoman"
* entry[=].resource.patient.display = "Eve Everywoman"